<!DOCTYPE html>
<html lang="en">
  	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <title>PHP Phalcon Framework</title>

	    <!-- Bootstrap -->
	    <link href="css/bootstrap.min.css" rel="stylesheet">

	    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	    <!--[if lt IE 9]>
	      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	    <![endif]-->
  	</head>
  	<body>

  		<div class="jumbotron">
	  		<div class="container">
	  			<h1>Hello from Phalcon!</h1>
		  		<p class="text-right">
			  		<?php 
			  			use Phalcon\Tag;
			  		?>
		  			<?php echo Tag::linkTo(
						array("signup", "Sign Up Here!", "class" => "btn btn-danger")); ?>
				</p>
	  		</div>
  		</div>

  		<div class="container">
  			<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4"></div>
  			<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
  				<?php 
				use Phalcon\Forms\Form,
				    Phalcon\Forms\Element\Text,
				    Phalcon\Forms\Element\Select;

					$form = new Form();

					$form->add(new Text("name", array("class" => "form-control")));

					$form->add(new Text("telephone", array("class" => "form-control")));

					$form->add(new Select("telephoneType", array(
					    'H' => 'Home',
					    'C' => 'Cell'
					), array("class" => "form-control")));?>

				<h1>Contact us</h1>

				<form method="post">

				    <p>
				        <label>Name</label>
				        <?php echo $form->render("name") ?>
				    </p>

				    <p>
				        <label>Telephone</label>
				        <?php echo $form->render("telephone") ?>
				    </p>

				    <p>
				        <label>Type</label>
				        <?php echo $form->render("telephoneType") ?>
				    </p>

				    <p>
				        <input type="submit" value="Save" class="btn btn-primary" />
				    </p>

				</form>
  			</div>
  		</div>

	    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	    <!-- Include all compiled plugins (below), or include individual files as needed -->
	    <script src="js/bootstrap.min.js"></script>
	    <script type='text/javascript' id="__bs_script__">//<![CDATA[
   		document.write("<script async src='//HOST:3000/browser-sync/browser-sync-client.1.9.0.js'><\/script>".
   			replace(/HOST/g, location.hostname).replace(/PORT/g, location.port)); //]]></script>
  	</body>
</html>