<!DOCTYPE html>
<html lang="en">
  	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <title>PHP Phalcon</title>

	    <!-- Bootstrap -->
	    <link href="css/bootstrap.min.css" rel="stylesheet">

	    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	    <!--[if lt IE 9]>
	      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	    <![endif]-->
  	</head>
  	<body>

  		<div class="container">
		  	<div class="row" style="margin-top: 50px">
			  	<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4"></div>
			  	<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
			  		<?php use Phalcon\Tag; ?>

					<h2>Sign up using this form</h2>

					<?php echo Tag::form("signup/register"); ?>

					 <p>
					    <label for="name">Name</label>
					    <?php echo Tag::textField(array("name", "class" => "form-control")) ?>
					 </p>

					 <p>
					    <label for="email">E-Mail</label>
					    <?php echo Tag::emailField(array("email", "class" => "form-control")) ?>
					 </p>

					 <p class="text-right">
					    <?php echo Tag::submitButton(array("Register", "class" => "btn btn-primary")) ?>
					 </p>

					</form>
			  	</div>
		  	</div>
  		</div>

	    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	    <!-- Include all compiled plugins (below), or include individual files as needed -->
	    <script src="js/bootstrap.min.js"></script>
	    <script type='text/javascript' id="__bs_script__">//<![CDATA[
   		document.write("<script async src='//HOST:3000/browser-sync/browser-sync-client.1.9.0.js'><\/script>".replace(/HOST/g, location.hostname).replace(/PORT/g, location.port)); //]]></script>
  	</body>
</html>