<!DOCTYPE html>
<html lang="en">
  	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <title>PHP Phalcon Framework</title>

	    <!-- Bootstrap -->
	    <link href="css/bootstrap.min.css" rel="stylesheet">

	    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	    <!--[if lt IE 9]>
	      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	    <![endif]-->
  	</head>
  	<body>

		<?php use Phalcon\Tag; ?>

  		<div class="container">
	  		<div class="page-header">
	  			<div class="row">
	  				<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
	  					<h1>Phalcon <small>The fastest PHP framework!</small></h1>
	  				</div>
	  				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
	  					<ul class="nav nav-pills pull-right" style="margin-top: 7%">
						  	<li role="presentation">
						  		<?php echo Tag::linkTo( array("index", "Home")); ?>
						  	</li>
						  	<li role="presentation">
						  		<?php echo Tag::linkTo( array("about", "About")); ?>
						  	</li>
						  	<li role="presentation" class="active">
						  		<?php echo Tag::linkTo( array("contact", "Contact")); ?>
						  	</li>
						</ul>
	  				</div>
	  			</div>
	  		</div>

	  		<div class="jumbotron">
	  			<h1>This is Contact page!</h1>
		  		<p class="text-right">
		  			<?php echo Tag::linkTo( array("signup", "Sign Up Here!", "class" => "btn btn-danger")); ?>
				</p>
	  		</div>

	  		<div class="row" style="padding: 50px 100px 0 100px">
	  			<?php

				use Phalcon\Forms\Form,
				    Phalcon\Forms\Element\Text,
				    Phalcon\Forms\Element\Email,
				    Phalcon\Forms\Element\Select,
				    Phalcon\Forms\Element\Textarea,
				    Phalcon\Validation\Validator\PresenceOf,
				    Phalcon\Validation\Validator\StringLength;

					# instaciranje polja forme
					$name = new Text("name");
					$email = new Email("email");
					$gender = new Select("gender", 
						array( 'M' => 'Male', 'F' => 'Female' ));
					$text = new Textarea("text");

					# instanciranje validatora za data polja
					$name->addValidator(new PresenceOf(array(
					    'message' => 'The name is required'
					)));

					$email->addValidator(new PresenceOf(array(
					    'message' => 'The email is required'
					)));

					$text->addValidator(new PresenceOf(array(
					    'message' => 'The message is required'
					)));

					$form = new Form();

					$form->add($name); $form->add($email);
					$form->add($gender); $form->add($text); ?>	

	  			<p style="text-center">
	  				<?php if (isset($status)) echo $status; ?>
		        </p>

				<form action="contact/register" method="POST" role="form">

	  				<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
					
						<div class="form-group">
							<?php echo $form->render("name", array(
								"class" => "form-control", "placeholder" => "Your name")); ?>
						</div>
					
						<div class="form-group">
							<?php echo $form->render("email", array(
								"class" => "form-control", "placeholder" => "Your email")); ?>
						</div>
					
						<div class="form-group">
							<?php echo $form->render("gender", array( "class" => "form-control")); ?>
						</div>
					
					</div>

	  				<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">

						<div class="form-group">
							<?php echo $form->render("text", array( 
								"class" => "form-control", "rows" => 6, "placeholder" => "Your message")); ?>
						</div>
					</div>

					<div class="text-center">
						<button type="submit" class="btn btn-primary">Send mesage</button></div>
	  			</form>	
	  		</div>
  		</div>

	    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	    <script src="js/jquery-1.11.2.min.js"></script>
	    <!-- Include all compiled plugins (below), or include individual files as needed -->
	    <script src="js/bootstrap.min.js"></script>
  	</body>
</html>