<!DOCTYPE html>
<html lang="en">
  	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <title>PHP Phalcon Framework</title>

	    <!-- Bootstrap -->
	    <link href="css/bootstrap.min.css" rel="stylesheet">

	    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	    <!--[if lt IE 9]>
	      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	    <![endif]-->
  	</head>
  	<body>

  		<?php use Phalcon\Tag; ?>

  		<div class="container">
	  		<div class="page-header">
	  			<div class="row">
	  				<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
	  					<h1>Phalcon <small>The fastest PHP framework!</small></h1>
	  				</div>
	  				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
	  					<ul class="nav nav-pills pull-right" style="margin-top: 7%">
						  	<li role="presentation" class="active">
						  		<?php echo Tag::linkTo( array("index", "Home")); ?>
						  	</li>
						  	<li role="presentation">
						  		<?php echo Tag::linkTo( array("about", "About")); ?>
						  	</li>
						  	<li role="presentation">
						  		<?php echo Tag::linkTo( array("contact", "Contact")); ?>
						  	</li>
						</ul>
	  				</div>
	  			</div>
	  		</div>

	  		<div class="jumbotron">
	  			<h1>This is Home page!</h1>
		  		<p class="text-right">
		  			<?php echo Tag::linkTo( array("signup", "Sign Up Here!", "class" => "btn btn-danger")); ?>
				</p>
	  		</div>
  		</div>

	    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	    <script src="js/jquery-1.11.2.min.js"></script>
	    <!-- Include all compiled plugins (below), or include individual files as needed -->
	    <script src="js/bootstrap.min.js"></script>
  	</body>
</html>